### ISSUE TITLE
Readme would be nice

### ISSUE THREAD

**Issue by Alphavader** [vercel/nextjs-planetscale-nextauth-tailwindcss-template#11]
Hi,

ive cloned and deployed the repo via vercel and it does not start.
I assume, that i need to put some information in the .env file.
(and update nextjs to a stable version?) 

However a small readme would be nice. 
The project seems like a nice starter - but is not usable for me

**Comment by leerob** [comment]
Adding stuff here! https://github.com/vercel/nextjs-planetscale-nextauth-tailwindcss-template/pull/12
