### ISSUE TITLE
Newer packages of tremor components require "use client"

### ISSUE THREAD

**Issue by Cmosley** [vercel/nextjs-planetscale-nextauth-tailwindcss-template#17]
Route: 'Playground'
Looks like the grid component in the newest version of tremor breaks the page if you don't specify 'use client' 

"@tremor/react": "^3.0.1",

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-planetscale-nextauth-tailwindcss-template/commit/58e6d5169bdc161d74d37181d34c525220af4aa2
