### ISSUE TITLE
Type error when deploying Next.js site to Vercel: "Property 'onClick' does not exist on type 'Disclosure.Button'"

### ISSUE THREAD

**Issue by enzo-mourany** [vercel/nextjs-planetscale-nextauth-tailwindcss-template#4]
I encountered the following error when deploying my Next.js website to Vercel:

```typescript
Type error: Type '{ children: string; onClick: () => Promise<undefined>; className: string; }' is not assignable to type 'IntrinsicAttributes & CleanProps<"button", ButtonPropsWeControl> & OurProps<"button", ButtonRenderPropArg> & { ...; } & { ...; }'.
  Property 'onClick' does not exist on type 'IntrinsicAttributes & CleanProps<"button", ButtonPropsWeControl> & OurProps<"button", ButtonRenderPropArg> & { ...; } & { ...; }'.
  ...
````

The error seems to be related to a type mismatch between the props passed to a component and the types expected by the component. Specifically, the error indicates that the onClick property does not exist on the Disclosure.Button component

Any guidance on how to resolve this issue would be greatly appreciated. Thank you

<img width="1207" alt="Screenshot 2023-03-06 at 22 01 16" src="https://user-images.githubusercontent.com/90501970/223230789-4560b543-07d0-4ceb-9001-e16671b0582d.png">

**Comment by picklebrownie** [comment]
I clicked the "Clone & Deploy" button to start this, and the build failed on Vercel with the same error. I have not made any changes to the codebase. I'll look into it and update here if I resolve the issue. 

<img width="1222" alt="Screen Shot 2023-03-07 at 1 58 03 PM" src="https://user-images.githubusercontent.com/72936296/223523565-d8d87449-bd37-4b8a-a4bb-978a17e09661.png">

**Comment by b3nelly2** [comment]
> I clicked the "Clone & Deploy" button to start this, and the build failed on Vercel with the same error. I have not made any changes to the codebase. I'll look into it and update here if I resolve the issue.
> 
> <img alt="Screen Shot 2023-03-07 at 1 58 03 PM" width="1222" src="https://user-images.githubusercontent.com/72936296/223523565-d8d87449-bd37-4b8a-a4bb-978a17e09661.png">

Having the same issue over here.

**Comment by b3nelly2** [comment]
> Hey, I don't think that's the code provided by this template, is it?
> 
> Anyway, you're looking at a TypeScript error there (it should also fail with `next build` locally) 🙏

This is the code provided in the template...

**Comment by leerob** [comment]
Oh, my bad! I didn't realize there was a type error on `main`.

**Comment by b3nelly2** [comment]
Not 100% on this but created a temporary fix that is working for me.

https://github.com/b3nelly2/admin-dashboard-tailwind-planetscale-react-nextjs/commit/7d669ab1ba25879e7cfd39acf911edca4bd07675

**Comment by aaronkantrowitz** [comment]
I'm receiving this error when I click clone & deploy as well.
